"""create risk metrics table

Revision ID: 506f33441a55
Revises: 279d6fca6a47
Create Date: 2026-06-12 01:40:31.267558
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '506f33441a55'
down_revision: Union[str, None] = '279d6fca6a47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_metrics',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('calculation_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('lookback_days', sa.Integer(), nullable=False),
    sa.Column('risk_free_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('annualized_return', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('annualized_volatility', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('beta', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('alpha', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('information_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('tracking_error', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('max_drawdown_start', sa.Date(), nullable=True),
    sa.Column('max_drawdown_end', sa.Date(), nullable=True),
    sa.Column('current_drawdown', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('var_95', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('var_99', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('cvar_95', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('cvar_99', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('downside_deviation', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('calmar_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('skewness', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('kurtosis', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('benchmark', sa.String(length=20), nullable=True),
    sa.Column('return_series', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('drawdown_series', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_metrics_calculation_date'), 'risk_metrics', ['calculation_date'], unique=False)
    op.create_index(op.f('ix_risk_metrics_portfolio_id'), 'risk_metrics', ['portfolio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_metrics_portfolio_id'), table_name='risk_metrics')
    op.drop_index(op.f('ix_risk_metrics_calculation_date'), table_name='risk_metrics')
    op.drop_table('risk_metrics')
    # ### end Alembic commands ###
