"""create health scores table

Revision ID: d7d491041870
Revises: 08c8ab56c54d
Create Date: 2026-06-12 01:51:58.022508
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = 'd7d491041870'
down_revision: Union[str, None] = '08c8ab56c54d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_scores',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('calculation_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('overall_grade', sa.String(length=20), nullable=False),
    sa.Column('overall_explanation', sa.Text(), nullable=False),
    sa.Column('diversification_score', sa.Integer(), nullable=False),
    sa.Column('diversification_grade', sa.String(length=20), nullable=False),
    sa.Column('diversification_details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_grade', sa.String(length=20), nullable=False),
    sa.Column('risk_details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('performance_score', sa.Integer(), nullable=False),
    sa.Column('performance_grade', sa.String(length=20), nullable=False),
    sa.Column('performance_details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('efficiency_score', sa.Integer(), nullable=False),
    sa.Column('efficiency_grade', sa.String(length=20), nullable=False),
    sa.Column('efficiency_details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('recommendations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_scores_calculation_date'), 'health_scores', ['calculation_date'], unique=False)
    op.create_index(op.f('ix_health_scores_portfolio_id'), 'health_scores', ['portfolio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_scores_portfolio_id'), table_name='health_scores')
    op.drop_index(op.f('ix_health_scores_calculation_date'), table_name='health_scores')
    op.drop_table('health_scores')
    # ### end Alembic commands ###
